language: php
php:
  # - '8.0'
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer --prefer-dist --classmap-authoritative install --ignore-platform-reqs

jobs:
  include:
    - name: phpunit
      stage: test
      script: vendor/bin/phpunit
#    - name: phan
#      script: vendor/bin/phan
#    - name: psalm
#      script: vendor/bin/psalm
#    - name: phpcs
#      script: vendor/bin/phpcs